name: Ardour CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install dependancies
        run: |
          sudo apt install -y libgtkmm-2.4-dev python gcc g++ libatk1.0-0 aubio-tools libaubio-dev automake libboost-all-dev libcairomm-1.0-dev curl libatkmm-1.6-dev autoconf bison libcairo2-dev cmake libcppunit-dev expat libflac-dev libfftw3-dev libfreetype6 gettext gnome-common gobject-introspection  gtk-doc-tools gtk2-engines libgtk2.0-dev libgtkmm-3.0-dev libharfbuzz-dev intltool itstool wget libarchive-dev libffi-dev liblo-dev libogg-dev libpng-dev libsamplerate-dev libsigc++-2.0-dev libsndfile-dev libtool libusb-1.0-0-dev libvorbis-dev libwebsockets-dev libxml2 libxslt-dev lilv-utils liblrdf0-dev lv2-dev m4 libnss3 libnss3-dev libnsspem libpango-1.0-0 libpangomm-1.4-dev libpcre3 libpcre3-dev libpixman-1-dev pkg-config raptor2-utils rasqal-utils python3-rdflib libreadline-dev redland-utils librubberband-dev libserd-dev libsord-dev libsratom-dev libsuil-dev  libncurses5-dev libtiff-dev util-linux vamp-plugin-sdk xz-utils zlib1g-dev libjack-dev libc6-dev alsa-tools alsa-utils alsa-base libasound2-dev libpulse-dev libglib2.0-dev libtag1-dev rubberband-vamp clang libudev-dev libcwiid-dev liblilv-dev
          wget https://www.ijg.org/files/jpegsrc.v9a.tar.gz && tar xf jpegsrc.v9a.tar.gz && rm jpegsrc.v9a.tar.gz && cd jpeg-9a && ./configure --enable-shared && make && sudo make install && rm -rf jpeg-9a
      - name: build
        working-directory: ./ardour
        run: | 
          ./waf configure
          ./waf
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ardour-linux-x86-latest
          path: ardour/
